version: '3.8'

services:
  db:
    image: postgres:16
    container_name: database
    environment:
      POSTGRES_DB: car_parts_shop
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build: backend/
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m


volumes:
  pgdata: